### ISSUE TITLE
can't install latest version under ruby 3.1.1

### ISSUE THREAD

**Issue by gsar** [abrom/henkei#25]
The gemspec seems to limit the ruby version to `< 3.1.0`. Is there a good reason for that?

**Comment by abrom** [comment]
Just haven't tested against Ruby 3.1 as yet. I've created #26 to do just that 😉

**Comment by abrom** [comment]
Released in [v2.2.1.2](https://rubygems.org/gems/henkei/versions/2.2.1.2)
