### ISSUE TITLE
Question regarding image extraction and future maintenance of the project

### ISSUE THREAD

**Issue by diegocostares** [abrom/henkei#48]
Hi, I’m using **henkei** to extract text and metadata from documents. I was wondering:

1. Is there a way to extract images from files (e.g., PDFs, DOCX) with henkei? If not, are there plans to add this functionality in the future?
2. Will the project continue to be actively maintained and updated going forward?

Thanks!

**Comment by abrom** [comment]
1. You mean [Reading text from inside images (OCR)](https://github.com/abrom/henkei?tab=readme-ov-file#reading-text-from-inside-images-ocr)
2. You seem to be suggesting that it currently isn't actively maintained? The latest release supports the latest Tika release 😉

**Comment by abrom** [comment]
1. If you're referring to extracting the actual images themselves as images, you're looking at the wrong tool. From the first paragraph of the Tika website:

> The Apache Tika™ toolkit detects and extracts metadata and text

And Henkei is a basic wrapper around Tika.

If that is your goal I'd suggest you look at something like https://pdfbox.apache.org/ for PDFs and you can just use `zip` to extract images from a DOCX 😄 (DOCX is just a structured zip file with images stored inside)

**Comment by diegocostares** [comment]
Thank you very much, it is clearer to me now.
